mengenlehre-loesung.pdf: mengenlehre-loesung.ps
	ps2pdf mengenlehre-loesung.ps
	open mengenlehre-loesung.pdf

mengenlehre.ps: mengenlehre.dvi
	dvips -o mengenlehre.ps mengenlehre.dvi

mengenlehre.dvi: mengenlehre.tex 
	latex mengenlehre.tex

mengenlehre-loesung.pdf: mengenlehre-loesung.ps
	ps2pdf mengenlehre-loesung.ps
	open mengenlehre-loesung.pdf

mengenlehre-loesung.ps: mengenlehre-loesung.dvi
	dvips -o mengenlehre-loesung.ps mengenlehre-loesung.dvi

mengenlehre-loesung.dvi: mengenlehre-loesung.tex 
	latex mengenlehre-loesung.tex