---
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

version: "2"

services:
  notebook:
    build: .
    image: my-notebook
    container_name: stroetmann-logic-ts-notebook
    volumes:
      - ".:/home/jovyan/00-TypeScript"
    ports:
      - "8888:8888"
