probe-klausur-13: probe-klausur-13.pdf
	open probe-klausur-13.pdf

probe-klausur-13.pdf: probe-klausur-13.ps
	ps2pdf probe-klausur-13.ps

probe-klausur-13.ps: probe-klausur-13.dvi
	dvips -o probe-klausur-13.ps probe-klausur-13.dvi

probe-klausur-13.dvi: probe-klausur-13.tex  
	latex probe-klausur-13.tex

probe-klausur-11: probe-klausur-11.pdf
	open probe-klausur-11.pdf

probe-klausur-11.pdf: probe-klausur-11.ps
	ps2pdf probe-klausur-11.ps

probe-klausur-11.ps: probe-klausur-11.dvi
	dvips -o probe-klausur-11.ps probe-klausur-11.dvi

probe-klausur-11.dvi: probe-klausur-11.tex  
	latex probe-klausur-11.tex

loesung-12: loesung-12.pdf
	open loesung-12.pdf

loesung-12.pdf: loesung-12.ps
	ps2pdf loesung-12.ps

loesung-12.ps: loesung-12.dvi
	dvips -o loesung-12.ps loesung-12.dvi

loesung-12.dvi: loesung-12.tex  
	latex loesung-12.tex


loesung-11: loesung-11.pdf
	open loesung-11.pdf

loesung-11.pdf: loesung-11.ps
	ps2pdf loesung-11.ps

loesung-11.ps: loesung-11.dvi
	dvips -o loesung-11.ps loesung-11.dvi

loesung-11.dvi: loesung-11.tex  
	latex loesung-11.tex

